# Generated by Django 5.0.6 on 2024-05-24 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myzei', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitions',
            name='employe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Employ', to='myzei.employee'),
        ),
    ]
