# Generated by Django 5.0.6 on 2024-05-24 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myzei', '0002_alter_exhibitions_employe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibit',
            name='keeper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myzei.employee'),
        ),
    ]
