# Generated by Django 5.0.6 on 2024-05-23 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('myzei', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myzei.client'),
        ),
        migrations.AddField(
            model_name='order',
            name='exhibitions',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myzei.exhibitions'),
        ),
        migrations.AddField(
            model_name='order',
            name='promocode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.promocode'),
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.answer'),
        ),
        migrations.AddField(
            model_name='review',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myzei.client'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='employee_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myzei.employeeposition'),
        ),
    ]
