# Generated by Django 5.0.6 on 2024-05-24 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
        ('myzei', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='exhibitions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myzei.exhibitions'),
        ),
    ]
